version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - abeckdev
  assignees:
  - abeckdev
  ignore:
  - dependency-name: MailKit
    versions:
    - 2.11.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
