name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Check directory
      uses: jcblw/bash@master
      with:
        args: "pwd ls"
      
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Pack with dotnet
      run: dotnet pack --configuration Release
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: drop
        path: src/abeckdev.common/bin/Release/
